const STOP_LOADING = "STOP_LOADING";
const SET_QUIZ_SETUP = "SET_QUIZ_SETUP";
const SET_LOADING = "SET_LOADING";
const SET_QUIZ_STATE = "FETCH_QUIZ";
const NO_DATA_RECEIVED = "NO_DATA_RECEIVED";
const HANDLE_ERROR = "HANDLE_ERROR";
const HANDLE_NEXT_QUESTION = "HANDLE_NEXT_QUESTION";
const HANDLE_USER_RESPONSE = "HANDLE_USER_RESPONSE";
const HANDLE_RESTART_GAME = "HANDLE_RESTART_GAME";
const HANDLE_PLAY_AGAIN = "HANDLE_PLAY_AGAIN";

export {
  SET_LOADING,
  SET_QUIZ_SETUP,
  STOP_LOADING,
  SET_QUIZ_STATE,
  NO_DATA_RECEIVED,
  HANDLE_ERROR,
  HANDLE_NEXT_QUESTION,
  HANDLE_USER_RESPONSE,
  HANDLE_RESTART_GAME,
  HANDLE_PLAY_AGAIN,
};
