const SET_LOADING = "SET_LOADING";
const STOP_LOADING = "STOP_LOADING";
const SET_STORIES = "SET_STORIES";
const REMOVE_STORY = "REMOVE_STORY";
const HANDLE_PAGE = "HANDLE_PAGE";
const HANDLE_SEARCH = "HANDLE_SEARCH";
const HANDLE_ERROR = "HANDLE_ERROR";

export {
  SET_LOADING,
  STOP_LOADING,
  SET_STORIES,
  REMOVE_STORY,
  HANDLE_PAGE,
  HANDLE_SEARCH,
  HANDLE_ERROR,
};
